# Generated by Django 5.0 on 2023-12-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="picture1",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
